name: Publish Atlas API

on:
  workflow_dispatch:
  push:
    tags:
      - v*

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Clone & Publish
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - run: sbt publish
